### ISSUE TITLE
Overriding RABBIT_IS_ASYNCHRONOUS default is impossible

### ISSUE THREAD

**Issue by ghost** [IS-ENES-Data/esgf-pid#4]
We are using esgfpid within the [ES-DOC errata web-service](https://github.com/ES-DOC/esdoc-errata-ws).  We need to use esgfpid in **synchronous** mode as the calling thread is running in an event loop.

I assumed it was as simple as:

`esgfpid.defaults.RABBIT_IS_ASYNCHRONOUS = False`

However @ line 19 within the **esgfpid.rabbit.rabbit.py** you set a module level work variable:

`ASYNCHRONOUS = esgfpid.defaults.RABBIT_IS_ASYNCHRONOUS`

As rabbit.py ASYNCHRONOUS variable is assigned at import time, it cannot be subequently overridden.

The resolution of this issue is simple:

1. Delete the work variable;

2. Import the defaults module:

    `from esgfpid import defaults`

3. Replace ASYNCHRONOUS defaults.RABBIT_IS_ASYNCHRONOUS.

**Comment by merretbuurman** [comment]
Hi Mark,
the synchronous module has not been touched/maintained for ages. I had started developing the library in the synchronous mode, but then the decision was taken to switch to asynchronous and continue developing only that. I guess I should have deleted the entire module and that flag in the defaults.

As I am currently working on a new task it will not be possible for me to fix/recover the synchronous module, so I will delete it from the code base in the next release. However, if you feel like, you're welcome to fix it.

(Closing this issue, as I will not solve it, but can be reopened in case someone else will work on it).

**Comment by merretbuurman** [comment]
PS: As the synchronous module is relatively simple compared to the asynchronous, multi-threaded one, it may be quite simple to fix it.
